export const ITALIAN_PROVINCIAL_DATA: Record<string, string[]> = {
    "Abruzzo": ["Chieti", "L'Aquila", "Pescara", "Teramo"],
    "Basilicata": ["Matera", "Potenza"],
    "Calabria": ["Catanzaro", "Cosenza", "Crotone", "Reggio Calabria", "Vibo Valentia"],
    "Campania": ["Avellino", "Benevento", "Caserta", "Napoli", "Salerno"],
    "Emilia-Romagna": ["Bologna", "Ferrara", "Forlì-Cesena", "Modena", "Parma", "Piacenza", "Ravenna", "Reggio Emilia", "Rimini"],
    "Friuli-Venezia Giulia": ["Gorizia", "Pordenone", "Trieste", "Udine"],
    "Lazio": ["Frosinone", "Latina", "Rieti", "Roma", "Viterbo"],
    "Liguria": ["Genova", "Imperia", "La Spezia", "Savona"],
    "Lombardia": ["Bergamo", "Brescia", "Como", "Cremona", "Lecco", "Lodi", "Mantova", "Milano", "Monza e della Brianza", "Pavia", "Sondrio", "Varese"],
    "Marche": ["Ancona", "Ascoli Piceno", "Fermo", "Macerata", "Pesaro e Urbino"],
    "Molise": ["Campobasso", "Isernia"],
    "Piemonte": ["Alessandria", "Asti", "Biella", "Cuneo", "Novara", "Torino", "Verbano-Cusio-Ossola", "Vercelli"],
    "Puglia": ["Bari", "Barletta-Andria-Trani", "Brindisi", "Foggia", "Lecce", "Taranto"],
    "Sardegna": ["Cagliari", "Nuoro", "Oristano", "Sassari", "Sud Sardegna"],
    "Sicilia": ["Agrigento", "Caltanissetta", "Catania", "Enna", "Messina", "Palermo", "Ragusa", "Siracusa", "Trapani"],
    "Toscana": ["Arezzo", "Firenze", "Grosseto", "Livorno", "Lucca", "Massa-Carrara", "Pisa", "Pistoia", "Prato", "Siena"],
    "Trentino-Alto Adige": ["Bolzano", "Trento"],
    "Umbria": ["Perugia", "Terni"],
    "Valle d'Aosta": ["Valle d'Aosta"],
    "Veneto": ["Belluno", "Padova", "Rovigo", "Treviso", "Venezia", "Verona", "Vicenza"]
};

export const ITALIAN_REGIONS = Object.keys(ITALIAN_PROVINCIAL_DATA);

export const PROVINCE_TO_CODE: Record<string, string> = {
    "Agrigento": "AG",
    "Alessandria": "AL",
    "Ancona": "AN",
    "Aosta": "AO",
    "Valle d'Aosta": "AO",
    "Arezzo": "AR",
    "Ascoli Piceno": "AP",
    "Asti": "AT",
    "Avellino": "AV",
    "Bari": "BA",
    "Barletta-Andria-Trani": "BT",
    "Belluno": "BL",
    "Benevento": "BN",
    "Bergamo": "BG",
    "Biella": "BI",
    "Bologna": "BO",
    "Bolzano": "BZ",
    "Brescia": "BS",
    "Brindisi": "BR",
    "Cagliari": "CA",
    "Caltanissetta": "CL",
    "Campobasso": "CB",
    "Caserta": "CE",
    "Catania": "CT",
    "Catanzaro": "CZ",
    "Chieti": "CH",
    "Como": "CO",
    "Cosenza": "CS",
    "Cremona": "CR",
    "Crotone": "KR",
    "Cuneo": "CN",
    "Enna": "EN",
    "Fermo": "FM",
    "Ferrara": "FE",
    "Firenze": "FI",
    "Foggia": "FG",
    "Forlì-Cesena": "FC",
    "Frosinone": "FR",
    "Genova": "GE",
    "Gorizia": "GO",
    "Grosseto": "GR",
    "Imperia": "IM",
    "Isernia": "IS",
    "L'Aquila": "AQ",
    "La Spezia": "SP",
    "Latina": "LT",
    "Lecce": "LE",
    "Lecco": "LC",
    "Livorno": "LI",
    "Lodi": "LO",
    "Lucca": "LU",
    "Macerata": "MC",
    "Mantova": "MN",
    "Massa-Carrara": "MS",
    "Matera": "MT",
    "Messina": "ME",
    "Milano": "MI",
    "Modena": "MO",
    "Monza e della Brianza": "MB",
    "Napoli": "NA",
    "Novara": "NO",
    "Nuoro": "NU",
    "Oristano": "OR",
    "Padova": "PD",
    "Palermo": "PA",
    "Parma": "PR",
    "Pavia": "PV",
    "Perugia": "PG",
    "Pesaro e Urbino": "PU",
    "Pescara": "PE",
    "Piacenza": "PC",
    "Pisa": "PI",
    "Pistoia": "PT",
    "Pordenone": "PN",
    "Potenza": "PZ",
    "Prato": "PO",
    "Ragusa": "RG",
    "Ravenna": "RA",
    "Reggio Calabria": "RC",
    "Reggio Emilia": "RE",
    "Rieti": "RI",
    "Rimini": "RN",
    "Roma": "RM",
    "Rovigo": "RO",
    "Salerno": "SA",
    "Sassari": "SS",
    "Savona": "SV",
    "Siena": "SI",
    "Siracusa": "SR",
    "Sondrio": "SO",
    "Sud Sardegna": "SU",
    "Taranto": "TA",
    "Teramo": "TE",
    "Terni": "TR",
    "Torino": "TO",
    "Trapani": "TP",
    "Trento": "TN",
    "Treviso": "TV",
    "Trieste": "TS",
    "Udine": "UD",
    "Varese": "VA",
    "Venezia": "VE",
    "Verbano-Cusio-Ossola": "VB",
    "Vercelli": "VC",
    "Verona": "VR",
    "Vibo Valentia": "VV",
    "Vicenza": "VI",
    "Viterbo": "VT"
};

export const ALL_ITALIAN_PROVINCES: string[] = Array.from(
    new Set(Object.values(ITALIAN_PROVINCIAL_DATA).flat())
).sort((a, b) => a.localeCompare(b, 'it', { sensitivity: 'base' }));

